CREATE SCHEMA IF NOT EXISTS orders;

SET search_path TO orders;

CREATE TABLE IF NOT EXISTS orders (
    order_id        UUID PRIMARY KEY,
    state           VARCHAR(50) NOT NULL,
    cart_id         UUID        NOT NULL,
    delivery_id     UUID,
    payment_id      UUID,
    products_volume NUMERIC,
    products_weight NUMERIC,
    fragile         BOOLEAN,
    total_price     NUMERIC,
    products_price  NUMERIC,
    delivery_price  NUMERIC,
    user_id         VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_products (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   UUID        NOT NULL REFERENCES orders(order_id),
    product_id UUID        NOT NULL,
    quantity   INT         NOT NULL,
    CONSTRAINT unique_order_products UNIQUE (order_id, product_id)
)