CREATE SCHEMA IF NOT EXISTS shopping_cart;

SET search_path TO shopping_cart;

CREATE TABLE IF NOT EXISTS carts (
    id        UUID PRIMARY KEY,
    user_id   VARCHAR(50) NOT NULL,
    state     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_products (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    UUID        NOT NULL REFERENCES carts(id),
    product_id UUID        NOT NULL,
    quantity   INT         NOT NULL,
    CONSTRAINT unique_cart_products UNIQUE (cart_id, product_id)
);