CREATE SCHEMA IF NOT EXISTS warehouse;

SET search_path TO warehouse;

CREATE TABLE IF NOT EXISTS warehouse_product (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id VARCHAR(250) NOT NULL,
    product_id   UUID         NOT NULL,
    fragile      BOOLEAN      NOT NULL,
    width        NUMERIC,
    height       NUMERIC,
    depth        NUMERIC,
    weight       NUMERIC,
    quantity     NUMERIC      NOT NULL,
    CONSTRAINT unique_warehouse_product UNIQUE (warehouse_id, product_id)
);
